name: EAS Update (Beta)

on:
  release:
    types: [published]

jobs:
  eas-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Log in to Expo
        run: eas whoami || eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Publish update to "beta"
        env:
          EXPO_PUBLIC_API_ATLAS_BASE_URL: ${{ secrets.EXPO_PUBLIC_API_ATLAS_BASE_URL }}
          EXPO_PUBLIC_API_WARDEN_BASE_URL: ${{ secrets.EXPO_PUBLIC_API_WARDEN_BASE_URL }}
        run: |
          eas update --branch release --message "Automated release with EAS Update"
