name: EAS Update

on:
  release:
    types: [published]

jobs:
  eas-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Verify Expo authentication
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas whoami

      - name: Publish update to "beta"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_PUBLIC_API_ATLAS_BASE_URL: ${{ secrets.EXPO_PUBLIC_API_ATLAS_BASE_URL }}
          EXPO_PUBLIC_API_WARDEN_BASE_URL: ${{ secrets.EXPO_PUBLIC_API_WARDEN_BASE_URL }}
        run: |
          eas update --branch release ${{ github.ref_name }} --message "Automated release with EAS Update"
